---
- name: Generar Reporte de Disponibilidad de Instancias AWS
  hosts: all
  gather_facts: no
  connection: local

  vars:
    report_path: "/tmp/reporte_disponibilidad.csv"
    start_date: "2025-09-01T00:00:00Z"
    end_date: "2025-09-30T23:59:59Z"
    dias_del_mes: 30
    s3_endpoint_url: "http://172.17.0.1:9000"
    s3_bucket_name: "awx"

  tasks:
    - name: "Crear encabezado del archivo CSV"
      lineinfile:
        path: "{{ report_path }}"
        line: "Instance ID,Instance Name,Horas Encendido (Septiembre),Disponibilidad (%)"
        create: yes
        mode: '0644'
      delegate_to: localhost
      run_once: true

    - name: "Consultar métricas de CloudWatch para cada instancia"
      ansible.builtin.command: >
        aws cloudwatch get-metric-statistics
        --namespace AWS/EC2
        --metric-name CPUUtilization
        --dimensions Name=InstanceId,Value={{ inventory_hostname }}
        --start-time "{{ start_date }}"
        --end-time "{{ end_date }}"
        --period 3600
        --statistics SampleCount
        --profile awx_profile
      environment:
        AWS_SHARED_CREDENTIALS_FILE: "/tmp/aws_credentials"
        AWS_ACCESS_KEY_ID: "{{ lookup('tower.controller.credential', 'OXWACCINTNPRD').inputs.aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('tower.controller.credential', 'OXWACCINTNPRD').inputs.aws_secret_key }}"
        AWS_SESSION_TOKEN: "{{ lookup('tower.controller.credential', 'OXWACCINTNPRD').inputs.aws_session_token | default('') }}"
      register: cloudwatch_data
      delegate_to: localhost
      changed_when: false

    - name: "Procesar datos y calcular disponibilidad"
      vars:
        total_datapoints: "{{ (cloudwatch_data.stdout | from_json).Datapoints | sum(attribute='SampleCount') | int }}"
        horas_encendido: "{{ '%.2f' | format(total_datapoints) }}"
        total_horas_periodo: "{{ dias_del_mes * 24 }}"
        porcentaje_disponibilidad: "{{ '%.2f' | format((horas_encendido | float / total_horas_periodo | float) * 100) }}"
      lineinfile:
        path: "{{ report_path }}"
        line: >-
          {{ inventory_hostname }},
          {{ hostvars[inventory_hostname].ec2_tag_Name | default(inventory_hostname) }},
          {{ horas_encendido }},
          {{ porcentaje_disponibilidad }}%
      delegate_to: localhost

    - name: "Subir el reporte a un bucket S3"
      community.aws.s3_sync:
        bucket: "{{ s3_bucket_name }}"
        object: "reportes/disponibilidad-{{ lookup('pipe', 'date +%Y-%m-%d') }}.csv"
        src: "{{ report_path }}"
        mode: put
        aws_access_key: "{{ lookup('tower.controller.credential', 'S3 credentials').inputs.aws_access_key_id }}"
        aws_secret_key: "{{ lookup('tower.controller.credential', 'S3 credentials').inputs.aws_secret_key }}"
        endpoint_url: "{{ s3_endpoint_url }}"
      delegate_to: localhost
      run_once: true
