---
- name: Generar Reporte de Disponibilidad de Instancias AWS
  hosts: all
  gather_facts: no
  connection: local

  # --- CONFIGURA TUS VARIABLES AQUÍ ---
  vars:
    report_path: "/tmp/reporte_disponibilidad.csv"
    
    # --- RANGO DE FECHAS FIJO ---
    # Formato: AAAA-MM-DDTHH:MM:SSZ
    start_date: "2025-09-01T00:00:00Z"
    end_date: "2025-09-30T23:59:59Z"
    dias_del_mes: 30 # <-- Número de días en tu rango

    # --- Configuración S3 ---
    s3_endpoint_url: "http://172.17.0.1:9000"
    s3_bucket_name: "awx"

  # --- INICIO DE LAS TAREAS ---
  tasks:

    - name: "Crear encabezado del archivo CSV"
      lineinfile:
        path: "{{ report_path }}"
        line: "Instance ID,Instance Name,Horas Encendido (Septiembre),Disponibilidad (%)"
        create: yes
        mode: '0644'
      delegate_to: localhost
      run_once: true

    - name: "Consultar métricas de CloudWatch para cada instancia"
      ansible.builtin.command: >
        aws cloudwatch get-metric-statistics
        --namespace AWS/EC2
        --metric-name CPUUtilization
        --dimensions Name=InstanceId,Value={{ inventory_hostname }}
        --start-time "{{ start_date }}"
        --end-time "{{ end_date }}"
        --period 300
        --statistics SampleCount
      register: cloudwatch_data
      delegate_to: localhost
      changed_when: false

    - name: "Procesar datos y calcular disponibilidad"
      vars:
        total_datapoints: "{{ (cloudwatch_data.stdout | from_json).Datapoints | sum(attribute='SampleCount') | int }}"
        minutos_encendido: "{{ total_datapoints * 5 }}"
        horas_encendido: "{{ '%.2f' | format(minutos_encendido / 60) }}"
        total_horas_periodo: "{{ dias_del_mes * 24 }}"
        porcentaje_disponibilidad: "{{ '%.2f' | format((horas_encendido | float / total_horas_periodo | float) * 100) }}"
      lineinfile:
        path: "{{ report_path }}"
        line: >-
          {{ inventory_hostname }},
          {{ hostvars[inventory_hostname].ec2_tag_Name | default(inventory_hostname) }},
          {{ horas_encendido }},
          {{ porcentaje_disponibilidad }}%
      delegate_to: localhost

    - name: "Subir el reporte a un bucket S3"
      community.aws.s3_sync:
        bucket: "{{ s3_bucket_name }}"
        object: "reportes/disponibilidad-{{ lookup('pipe', 'date +%Y-%m-%d') }}.csv"
        src: "{{ report_path }}"
        mode: put
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        endpoint_url: "{{ s3_endpoint_url }}"
      delegate_to: localhost
      run_once: true
